apiVersion: v1
kind: Secret
metadata:
  name: evo-ai-secret
  namespace: evo-ai
type: Opaque
stringData:
  # Database
  POSTGRES_CONNECTION_STRING: "postgresql://postgres:root@evo-ai-postgres:5432/evo_ai"
  POSTGRES_PASSWORD: "root"
  POSTGRES_USER: "postgres"
  POSTGRES_DB: "evo_ai"
  
  # Redis
  REDIS_HOST: "evo-ai-redis"
  REDIS_PORT: "6379"
  REDIS_PASSWORD: "admin123"
  
  # App Secrets
  JWT_SECRET_KEY: "blatacetors"
  ENCRYPTION_KEY: "CaGyYg0PhFiB-iHw0PIfAOQ61Ch8VRVlhQZNCQB4YR8="
  
  # External Services
  SENDGRID_API_KEY: "your-sendgrid-api-key"
  SMTP_USER: "your-smtp-username"
  SMTP_PASSWORD: "your-smtp-password"
  LANGFUSE_PUBLIC_KEY: "pk-lf-f566e43d-34bb-470e-8c8a-e6a9d038546a"
  LANGFUSE_SECRET_KEY: "sk-lf-8b7f8420-e6cd-4626-a541-5bee5d31f6e5"
  
  # Seeder
  ADMIN_EMAIL: "salvador.dilio@gmail.com"
  ADMIN_INITIAL_PASSWORD: "Dilio1515**"
  DEMO_EMAIL: "salvador.admin@gmail.com"
  DEMO_PASSWORD: "Dilio1515**"
